name: CI for MWAA Staging

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: install Datafold SDK
      id: install-reqs
      run: pip install datafold-sdk

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'

    - uses: jwalton/gh-find-current-pr@v1.3.0
      id: findPR

    - uses: gagoar/invoke-aws-lambda@master
    # https://github.com/marketplace/actions/invoke-aws-lambda
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REGION: 'us-west-2'
        FunctionName: invokeDatafoldAirflowStagingDAG
        Payload: '{ "schema_name_postfix": "_PR_NUM_${{ steps.findPr.outputs.pr }}" }'

    - name: Identify diffed SQL files
      # - git diff main --name-only
      # - change spaces into new lines
      # - remove lines not containing .sql 
      # - remove dags/ prefix and .sql suffix
      run: echo $(git diff origin/${{ github.base_ref }} --name-only) | tr " " "\n" | sed '/\.sql/!d' |  sed -e "s/^dags\///" -e "s/.sql$//"  > ./git-diff.txt

    - name: execute py script # run file
      run: |
        python python/create_datafold_ci_submit_arg.py > ./diffs.txt
    
#    - name: Store diffs in file
#      run: echo '[{"prod":"DEMO.DATAFOLD_AIRFLOW.FORESTFIRES","pr":"DEMO.DATAFOLD_AIRFLOW_PR_NUM_${{ steps.findPr.outputs.pr }}.FORESTFIRES","pk":["ID"]},{"prod":"DEMO.DATAFOLD_AIRFLOW.BEARS","pr":"DEMO.DATAFOLD_AIRFLOW_PR_NUM_${{ steps.findPr.outputs.pr }}.BEARS","pk":["ID"]},{"prod":"DEMO.DATAFOLD_AIRFLOW.SQUIRRELS","pr":"DEMO.DATAFOLD_AIRFLOW_PR_NUM_${{ steps.findPr.outputs.pr }}.SQUIRRELS","pk":["ID"]}]' > ./diffs.txt
    
    - name: Kick off Datafold CI Run
      run: datafold ci submit --ci-config-id 286 --pr-num ${{ steps.findPr.outputs.pr }} --diffs ./diffs.txt
      env:
        DATAFOLD_API_KEY: ${{ secrets.DATAFOLD_API_KEY }}

