name: CI for MWAA Staging

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - '!main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: install Datafold SDK
      id: install-reqs
      run: pip install datafold-sdk

    - uses: actions/checkout@main
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'

    - uses: jwalton/gh-find-current-pr@v1.3.0
      id: findPR

    - uses: gagoar/invoke-aws-lambda@master
    # https://github.com/marketplace/actions/invoke-aws-lambda
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REGION: 'us-west-2'
        FunctionName: invokeDatafoldAirflowStagingDAG
        Payload: '{ "schema_name_postfix": "_PR_NUM_${{ steps.findPr.outputs.pr }}" }'

    - name: Kick off Datafold CI Run
      run: datafold ci submit --ci-config-id 286 --pr-num {{ steps.findPr.outputs.pr }} [{ "prod":"DEMO"."DATAFOLD_AIRFLOW"."FORESTFIRES", "pr":"DEMO"."DATAFOLD_AIRFLOW_PR_NUM_${{ steps.findPr.outputs.pr }}"."FORESTFIRES", "pk":["ID"] }]

