name: CI for MWAA Staging

on:
  pull_request:
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review
  push:
    branches:
      - '!main'

jobs:

  get_pr_num:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    
    steps:

    - uses: jwalton/gh-find-current-pr@v1.3.0
      id: findPR
    
    - run: echo "test=${{ steps.findPr.outputs.pr }}" >> "$GITHUB_OUTPUT"
      id: step1
      

  #test:
  #  needs: [get_pr_num]
  #  runs-on: ubuntu-latest
#
#    steps:

  #  - name: test output
  #    run: echo $OUTPUT1
  #    env:
  #      OUTPUT1: ${{needs.get_pr_num.outputs.output1}} # this is the pr num
      


  upload_to_s3:
    needs: get_pr_num
    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl private --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'


  lambda:
    needs: [upload_to_s3, get_pr_num]
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - uses: gagoar/invoke-aws-lambda@master
    # https://github.com/marketplace/actions/invoke-aws-lambda
      with:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        REGION: 'us-west-2'
        FunctionName: invokeDatafoldAirflowStagingDAG
        Payload: '{ "schema_name_postfix": "'"$OUTPUT1"'" }' 
      env:
        OUTPUT1: "_PR_NUM_"${{needs.get_pr_num.outputs.output1}} # this is the pr num
  

  diff:
    needs: [lambda, get_pr_num]
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@main
      with:
        fetch-depth: 0

    - name: Identify diffed SQL files
      # - git diff main --name-only
      # - change spaces into new lines
      # - remove lines not containing .sql 
      # - remove dags/ prefix and .sql suffix
      run: echo $(git diff origin/${{ github.base_ref }} --name-only) | tr " " "\n" | sed '/\.sql/!d' |  sed -e "s/^dags\///" -e "s/.sql$//"  > ./git-diff.txt

    - name: create diffs file
      run: python python/combined_script.py git-diff.txt > ./diffs.txt
    
    - name: add PR num to diffs file
      run: sed "s|__DATAFOLD_CI_PR_NUM|$OUTPUT1|g" diffs.txt > diffs_with_pr_num.txt
      env:
        OUTPUT1: ${{needs.get_pr_num.outputs.output1}} # this is the pr num

    - name: install Datafold SDK
      id: install-reqs
      run: pip install datafold-sdk

    - name: Kick off Datafold CI Run
      run: datafold ci submit --ci-config-id 286 --pr-num $OUTPUT1 --diffs ./diffs_with_pr_num.txt
      env:
        DATAFOLD_API_KEY: ${{ secrets.DATAFOLD_API_KEY }}
        OUTPUT1: ${{needs.get_pr_num.outputs.output1}} # this is the pr num

